Add docker-compose for the SonarQube
  If `docker-compose up -d` occurred error as follow

  ERROR: for sonar_db_1  UnixHTTPConnectionPool(host='localhost', port=None):
  Read timed out. (read timeout=120) ...

  We need to execute the below command and restart the docker

  $ export DOCKER_CLIENT_TIMEOUT=120
  $ export COMPOSE_HTTP_TIMEOUT=120

  ref: https://github.com/docker/compose/issues/3927